# Generated by Django 5.2.17 on 2026-10-03 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='اسم العميل')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات الطلب')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي الطلب')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='نسبة العربون %')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة العربون')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المتبقي')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='رقم عملية التحويل')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='orders/payment_proofs/', verbose_name='إثبات التحويل')),
                ('status', models.CharField(choices=[('pending', 'طلب جديد'), ('deposit_pending', 'بانتظار تأكيد العربون'), ('deposit_confirmed', 'تم تأكيد العربون'), ('processing', 'قيد التنفيذ'), ('ready', 'جاهز'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], default='pending', max_length=30, verbose_name='حالة الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج وقت الطلب')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر المنتج')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('customization_note', models.TextField(blank=True, verbose_name='ملاحظات التخصيص')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإجمالي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.order', verbose_name='الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='home.product', verbose_name='المنتج')),
            ],
        ),
    ]
