# Generated by Django 5.2.17 on 2026-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_number', models.CharField(default='01001404850', max_length=30, verbose_name='رقم المحفظة')),
                ('deposit_percentage', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='نسبة العربون %')),
                ('is_active', models.BooleanField(default=True, verbose_name='الإعدادات مفعلة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
    ]
