# Generated by Django 5.2.17 on 2026-10-03 18:48

import cloudinary.models
import home.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_category_image_alter_order_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[home.models.validate_image_size, home.models.validate_file_extension], verbose_name='صورة التصنيف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[home.models.validate_image_size, home.models.validate_file_extension], verbose_name='إثبات التحويل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[home.models.validate_image_size, home.models.validate_file_extension], verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[home.models.validate_image_size, home.models.validate_file_extension], verbose_name='الصورة'),
        ),
    ]
